open-craft/labxchange-xblocks

- CHANGELOG.rst
- labxchange_xblocks/__init__.py
- labxchange_xblocks/image_block.py
- labxchange_xblocks/public/css/image-xblock.css
- labxchange_xblocks/templates/image_student_view.html
- labxchange_xblocks/tests/image_block_test.py
- labxchange_xblocks/utils.py
Adds "caption" and "citation" fields. Both are displayed under the image.
Also ensures that `/static/blah.png` image URLs get rewritten in the `student_view_data`.
Test instructions: Create and/or edit one of these blocks in Studio. Note the new fields and how they appear:  
Test the student view data: upload an image to "Files & Uploads", then set the "Image URL" of this block to the "Studio URL" of that image (/static/blah). Then go to http://localhost:18000/courses/course-v1:LX+XB+TEST/xblock/block-v1:LX+XB+TEST+type@lx_image+block@fc3d2444da814658afcc971d7020e737/handler/v1_student_view_data where the course ID and the block ID are changed as needed, and note that the result contains an expanded URL:
```
"image_url": "/assets/courseware/v1/c72ed18a748a2d4d2a4d491128a91799/asset-v1:LX+X …
```
> Add caption & citation fields to image block

- labxchange_xblocks/__init__.py
- labxchange_xblocks/document_block.py
- labxchange_xblocks/utils.py
Adds a `public_view` so these XBlocks can be viewed by anonymous users.
An API in the new runtime to rewrite static URLs was renamed (to `transform_static_paths_to_urls`), so adding an asset with a URL like `/static/foo.png` was not working.
Also the document XBlock wasn't rewriting its URL at all in `student_view_data` (the image XBlock was, however).
> Fix static URLs, allow anonymous access

- .travis.yml
- labxchange_xblocks/assignment_block.py
- labxchange_xblocks/case_study_block.py
- labxchange_xblocks/document_block.py
- labxchange_xblocks/image_block.py
- labxchange_xblocks/narrative_block.py
- labxchange_xblocks/simulation_block.py
- labxchange_xblocks/tests/assignment_block_test.py
- labxchange_xblocks/utils.py
- manage.py
- requirements/travis.txt
- test_settings.py
- tox.ini
This updates the `student_view_data` of Assignment XBlocks so that for each child block:
1. `graded` is no longer based on the deprecated `graded` attribute, but rather `has_score` etc.
1. `max_attempts` is returned, if known
1. `weight` (maximum score that can be earned) is set, if known
This also updates the XBlock to properly handle `unit` children that themselves contain problems, e.g. if a Video or HTML is grouped together with a capa problem.
> Improve data that lx_assignment block provides about its children

- CHANGELOG.rst
- README.rst
- labxchange_xblocks/__init__.py
- labxchange_xblocks/audio_block.py
- labxchange_xblocks/public/css/audio-xblock.css
- labxchange_xblocks/templates/audio_student_view.html
- labxchange_xblocks/tests/audio_block_test.py
- setup.py
This XBlock renders arbitrary HTML and/or Javascript at the discretion of the author, making it particularly useful for displaying embed codes from sites such as SoundCloud or Stitcher.
> Implement the Audio XBlock

- Makefile
- labxchange_xblocks/__init__.py
- labxchange_xblocks/case_study_block.py
- labxchange_xblocks/templates/case_study_student_view.html
- labxchange_xblocks/tests/case_study_block_test.py
- labxchange_xblocks/utils.py
This is a breaking change to how case studies are structured to support customizable sections, multiple children per section, and inline html text content.
**Test instructions**:
- deploy this branch along with https://gitlab.com/opencraft/client/LabXchange/labxchange-dev/-/merge_requests/934
- follow test instructions with the labxchange PR
**Reviewers**:
> SE-2989 [LX-716] [SE-3026] [LX-793] add more customizable sections and attachments to case study

- labxchange_xblocks/audio_block.py
- labxchange_xblocks/public/js/audio-xblock.js
This pull request is about updating the audio xblock to use labxchange handler URL instead of directly using the edx since it is not possible because of security (CORS) issues.
Current problem:
The new URL that should be used:
- [SE-3111](https://tasks.opencraft.com/browse/SE-3111)
- Update your devstack to use this branch (`toxinu/audio-block-follow-up`)
- Create an audio asset in labxchange
- Add a transcript on it
- Check that the url called to retrieve the transcripts is labxchange api (which will request edx api) so that we don't get any CORS error (only visible on stage and production but not locally, that's why I didn't spot it before)
**Reviewer**
- @s0b0lev
> [SE-3111] Retrieve handler url from backend instead of frontend for audio xblock

- labxchange_xblocks/audio_block.py
- labxchange_xblocks/public/js/audio-xblock.js
This merge request is about using `GET` method instead of `POST` to retrieve audio sequences.
- [SE-3111](https://tasks.opencraft.com/browse/SE-3111)
- [LX-1294](https://tasks.opencraft.com/browse/LX-1294)
* :warning:️ You need to have [labxchange-xblocks](https://github.com/open-craft/labxchange-xblocks/pull/11) installed before
* Create an audio asset with a Soundcloud embed code
* Edit it and add a transcript
* Add another different transcript
* View the audio asset and check that you can see the different transcripts and change between them
* Check that when you change language, new sequences are retrieved using a `GET` request like that:
```
/api/xblock/v2/xblocks/lb:LabXchange:3877d1c2:lx_audio:1/handler/3-8a2dfb77df1 …
```
> [SE-3111] Use GET instead of POST to retrieve audio sequences

- labxchange_xblocks/audio_block.py
- labxchange_xblocks/templates/audio_student_view.html
This prevents confusion and buggy views when there are no transcripts,
by hiding the transcripts view entirely if no transcripts to display.
(It also removes some trailing space...)
**Test instructions**:
- create an audio asset with no transcripts
- view and verify that the transcripts element/bar is hidden
- add transcripts to the audio asset
- save and verify correct operation of the transcripts element
**Reviewers**:
> SE-3691 [LX-1723] Hide audio transcripts element if no transcripts

- .coverage
- labxchange_xblocks/__init__.py
- labxchange_xblocks/case_study_block.py
- labxchange_xblocks/templates/case_study_student_view.html
- labxchange_xblocks/tests/audio_block_test.py
- labxchange_xblocks/tests/case_study_block_test.py
- labxchange_xblocks/tests/document_block_test.py
- labxchange_xblocks/tests/image_block_test.py
- labxchange_xblocks/tests/simulation_block_test.py
- setup.py
[FAL-880](https://tasks.opencraft.com/browse/FAL-880)
This adds support for the teaching guide xblock.  It also fixes a bunch of unrelated broken tests.
**Test instructions**:
- install this in your devstack
- verify that tests pass
- continue testing with [opencraft/client/LabXchange/labxchange-dev#1319](https://gitlab.com/opencraft/client/LabXchange/labxchange-dev/-/merge_requests/1319)
**Reviewers**:
> FAL-880 [LX-1821] Teaching Guide xblock

- labxchange_xblocks/__init__.py
- labxchange_xblocks/annotated_video_block.py
This pull request is about returning the youtube video ID along with other view data so that the LX frontend can query the YouTube API to get extra details.
Note: This pull request should also increase the version number.
- [FAL-2117](https://tasks.opencraft.com/browse/FAL-2117)
Should be tested while reviewing internal PRs.
**Reviewers**
> [FAL-2117]  Return Youtube video ID with Annotated video xblock data

- labxchange_xblocks/__init__.py
- labxchange_xblocks/audio_block.py
- labxchange_xblocks/public/js/audio-xblock.js
- labxchange_xblocks/tests/audio_block_test.py
[FAL-2482](https://tasks.opencraft.com/browse/FAL-2482) | [LX-2242](https://tasks.opencraft.com/browse/LX-2242)
These changes are to support the transition from srt subtitles to inline html transcripts for audio blocks.
**Test instructions**:
- test as part of [opencraft/client/LabXchange/labxchange-dev!1532](https://gitlab.com/opencraft/client/LabXchange/labxchange-dev/-/merge_requests/1532)
- read the code and verify the logic is correct and desirable
> FAL-2482 [LX-2242] 

- labxchange_xblocks/__init__.py
- labxchange_xblocks/audio_block.py
**Description**
- [FAL-2483](https://tasks.opencraft.com/browse/FAL-2483)
- [LX-2243](https://tasks.opencraft.com/browse/LX-2243)
As a part of LX-2243, we are removing the transcript view for the audio xblock.
Transcript will no longer be shown in the xblock.
But for the first phase of deployment, we are just adding the student_view_handler so that the above is possible
**Testing Instructions**
1. Add the labxchange xblock into your labxchange devstack.
2. Add a new audio along with a transcript and save the video
3. Check the json is successfully returned via `student_view_user_state`
> Adding student_view_user_state for audio transcripts

- labxchange_xblocks/__init__.py
- labxchange_xblocks/image_block.py
- labxchange_xblocks/tests/image_block_test.py
**Description**
- [FAL-2631](https://tasks.opencraft.com/browse/FAL-2631)
- [LX-2094](https://tasks.opencraft.com/browse/LX-2094)
As a part of LX-2094, we want to support extended description for an image block
**Testing Instructions**
1. Add the labxchange xblock into your labxchange devstack.
2. Add a new image along with an extended description
3. Check that the extended description is visible on LX website
> Updates to image content type

- labxchange_xblocks/__init__.py
- labxchange_xblocks/annotated_video_block.py
- labxchange_xblocks/audio_block.py
- labxchange_xblocks/tests/annotated_video_block_test.py
- labxchange_xblocks/tests/audio_block_test.py
- labxchange_xblocks/tests/video_block_test.py
This merge request fixes two XBlocks that don't work properly on pathways:
1. `lx_audio`: removed code cruft and dependencies on transcript files (not used anymore).
2. `annotated_video`: fixed code that locates child video block to work in a generic way.
- [FAL-2925](https://tasks.opencraft.com/browse/FAL-2925)
- [LX-2552](https://tasks.opencraft.com/browse/LX-2552)
1. Install this branch on your devstack.
2. Check that `lx_audio` and `annotated_videos` continue working from the library (http://localhost:4556/library/items/lb:LabXchange:1109ec43:lx_annotated_video:1 and http://localhost:4556/library/items/lb:LabXchange:1f29b8d5:lx_audio:1).
3. Check that the modified blocks retain their behavior when logged out.
4. Create a pathways adding those …
> [LX-2552]: Fix `annotated_video` and `audio` blocks in pathways

- labxchange_xblocks/__init__.py
- labxchange_xblocks/question_block.py
- labxchange_xblocks/tests/question_block_test.py
- labxchange_xblocks/utils.py
Patch to the previous https://github.com/open-craft/labxchange-xblocks/pull/35, which allows xblock handlers to be called with a Django HttpRequest from within the LabXchange views.
Also fixes a bug caused by block caching and switching between using LX block types and edX block types.
Bumps version to `0.9.3`.
Can be tested with https://gitlab.com/opencraft/client/LabXchange/labxchange-dev/-/merge_requests/1684
**Author Notes & Concerns**
1. Needs to be deployed to edx-platform prior to enabling use of the LX runtime or lx block types.
> Fixes issues introduced by using lx_block_types for select users

- labxchange_xblocks/__init__.py
- labxchange_xblocks/fields.py
- labxchange_xblocks/video_block.py
LX calls the XBlock handler directly, and uses a slightly different request format.
This change handles that difference.
To be tested as part of https://gitlab.com/opencraft/client/LabXchange/labxchange-dev/-/merge_requests/1705
> LX-2480 fix: handles requests from LX's XBlockRuntime

- labxchange_xblocks/__init__.py
- labxchange_xblocks/tests/annotated_video_block_test.py
- labxchange_xblocks/video_block.py
LX calls the XBlock handler directly, and uses a slightly different request object.
This change handles that difference.
To be tested as part of https://gitlab.com/opencraft/client/LabXchange/labxchange-dev/-/merge_requests/1705
> fix: handles transcript requests from LX's XBlockRuntime

- labxchange_xblocks/__init__.py
- labxchange_xblocks/question_block.py
- labxchange_xblocks/tests/question_block_test.py
Parses optionresponse answers sent from Open edX and adds tests.
Open edX's CAPA single-answer optionresponse problems store the actual content of the chosen answer instead of the index.
This change allows us to match the student's answer content with the index of the chosen answer.
See https://gitlab.com/opencraft/client/LabXchange/labxchange-dev/-/merge_requests/1715
> Parses optionresponse answers sent from Open edX

- labxchange_xblocks/__init__.py
- labxchange_xblocks/question_block.py
- labxchange_xblocks/tests/question_block_test.py
Handles the case where `node.text == None`, which happens at times.
See [labxchange-dev MR.](https://gitlab.com/opencraft/client/LabXchange/labxchange-dev/-/merge_requests/1758)
> Fixes errors parsing question OLX

- labxchange_xblocks/__init__.py
- labxchange_xblocks/case_study_block.py
- labxchange_xblocks/tests/case_study_block_test.py
We're transitioning away from using replica items for XBlock children.
This PR modifies Case Study-like XBlocks to return original asset `usage_id`s instead of replica `usage_id`s for their child items (attachments and embedded).
* [FAL-3181](https://tasks.opencraft.com/browse/FAL-3181)
* [LX-2807](https://tasks.opencraft.com/browse/LX-2807)
See https://gitlab.com/opencraft/client/LabXchange/labxchange-dev/-/merge_requests/1835 for manual testing instructions.
See [README#Testing on devstack](https://github.com/open-craft/labxchange-xblocks#testing-on-devstack) to check unit tests.
> Case Studies/Teaching Guides return original item usage_ids for their children

- labxchange_xblocks/__init__.py
- labxchange_xblocks/case_study_block.py
- labxchange_xblocks/tests/case_study_block_test.py
Case Studies/Teaching Guides return original item usage_ids instead of replica `usage_ids`s for their child items (attachments and embedded).
[labxchange-xblocks#42 ](https://github.com/open-craft/labxchange-xblocks/pull/42) was only a partial fix -- it returned original item usage_ids for children of `sections`, but we forgot to fix the `attachment` items. This change fixes this.
* [FAL-3217](https://tasks.opencraft.com/browse/FAL-3217)
* https://app.asana.com/0/1202820371412061/1203271065106044/f
See https://gitlab.com/opencraft/client/LabXchange/labxchange-dev/-/merge_requests/TBD for manual testing instructions.
See [README#Testing on devstack](https://github.com/open-craft/labxchange-xblocks#testing-on-devstack) to check unit tests.
> Case Studies/Teaching Guides return original item usage_ids
